//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLC_LoadBank_SeparateVer.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RLC_LoadBank_SeparateVer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   상태 : Connected to System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Connected {
            get {
                return ResourceManager.GetString("App_Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Download Error !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Download_Error {
            get {
                return ResourceManager.GetString("App_Status_Download_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Download Complete !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Downloaded {
            get {
                return ResourceManager.GetString("App_Status_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Downloading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Downloading {
            get {
                return ResourceManager.GetString("App_Status_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : N/A과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Na {
            get {
                return ResourceManager.GetString("App_Status_Na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Save Complete !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Saved {
            get {
                return ResourceManager.GetString("App_Status_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Save Error !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_SavedError {
            get {
                return ResourceManager.GetString("App_Status_SavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 : START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_System_Start {
            get {
                return ResourceManager.GetString("App_Status_System_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 : STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_System_Stop {
            get {
                return ResourceManager.GetString("App_Status_System_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : 응답 시간 초과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Timeout {
            get {
                return ResourceManager.GetString("App_Status_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : 시간 동기 정보 전달과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_TimeSync {
            get {
                return ResourceManager.GetString("App_Status_TimeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : 시간 동기화 완료 !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_TimeSyncComplete {
            get {
                return ResourceManager.GetString("App_Status_TimeSyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : 시간 동기화 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_TimeSyncError {
            get {
                return ResourceManager.GetString("App_Status_TimeSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Update Error !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Update_Error {
            get {
                return ResourceManager.GetString("App_Status_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Update Complete !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Updated {
            get {
                return ResourceManager.GetString("App_Status_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Upload Error !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Upload_Error {
            get {
                return ResourceManager.GetString("App_Status_Upload_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Upload Complete ! 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Uploaded {
            get {
                return ResourceManager.GetString("App_Status_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태 : Uploading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_Status_Uploading {
            get {
                return ResourceManager.GetString("App_Status_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modbus 장치 : 연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusModbus_Connected {
            get {
                return ResourceManager.GetString("App_StatusModbus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modbus 장치 : 연결 끊김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusModbus_Disconnected {
            get {
                return ResourceManager.GetString("App_StatusModbus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modbus 장치 : 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusModbus_Error {
            get {
                return ResourceManager.GetString("App_StatusModbus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modbus 장치 : 연결 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusModbus_TryConnect {
            get {
                return ResourceManager.GetString("App_StatusModbus_TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RLC 장치 : 연결과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusNetwork_Connected {
            get {
                return ResourceManager.GetString("App_StatusNetwork_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RLC 장치 : 연결 끊김과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusNetwork_Disconnected {
            get {
                return ResourceManager.GetString("App_StatusNetwork_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RLC 장치 : 연결 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusNetwork_Error {
            get {
                return ResourceManager.GetString("App_StatusNetwork_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RLC 장치 : 연결 시도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string App_StatusNetwork_TryConnect {
            get {
                return ResourceManager.GetString("App_StatusNetwork_TryConnect", resourceCulture);
            }
        }
    }
}
